# -*- coding: utf-8 -*-
"""
Curated HK + US stock lists for local fuzzy search.

Why this exists:
  A-share search relies on a full ~5500-stock embedded list with pinyin data,
  enabling first-letter-abbreviation (首字母简写), full-pinyin, and non-contiguous
  fuzzy matching. HK/US previously only used Tencent's smartbox (prefix/substring
  on code/name only), so pinyin + fuzzy did not work.

  This module provides a curated set of the most-searched HK/US names so they get
  the exact same matching quality as A-shares. Tencent smartbox is still used as a
  fallback for the long tail (stocks not in this list).

HK codes: 5-digit zero-padded strings (e.g. "00700") — matches detect_market / analyzer.
US codes: uppercase tickers (e.g. "AAPL"). Names match what the analyzer displays.
"""

HK_US_STOCKS = {
    "HK": [
        ("00700", "腾讯控股"),
        ("09988", "阿里巴巴-W"),
        ("09618", "京东集团-SW"),
        ("03690", "美团-W"),
        ("01024", "快手-W"),
        ("09633", "农夫山泉"),
        ("01810", "小米集团-W"),
        ("02318", "中国平安"),
        ("00939", "建设银行"),
        ("01398", "工商银行"),
        ("03988", "中国银行"),
        ("01288", "农业银行"),
        ("01658", "邮储银行"),
        ("01988", "民生银行"),
        ("03968", "招商银行"),
        ("00941", "中国移动"),
        ("00762", "中国联通"),
        ("00728", "中国电信"),
        ("00857", "中国石油股份"),
        ("00883", "中国海洋石油"),
        ("00386", "中国石油化工股份"),
        ("02899", "紫金矿业"),
        ("01088", "中国铝业"),
        ("00788", "中国神华"),
        ("01071", "华电国际电力股份"),
        ("00902", "华能国际电力"),
        ("01898", "中煤能源"),
        ("00914", "海螺水泥"),
        ("01186", "中国铁建"),
        ("01600", "中国交通建设"),
        ("00390", "中国中铁"),
        ("01199", "中远海控"),
        ("01138", "中远海能"),
        ("01919", "中远海发"),
        ("00388", "香港交易所"),
        ("01299", "友邦保险"),
        ("02388", "中银香港"),
        ("00005", "汇丰控股"),
        ("00011", "恒生银行"),
        ("00023", "东亚银行"),
        ("00016", "新鸿基地产"),
        ("00012", "恒基兆业地产"),
        ("01113", "长实集团"),
        ("00823", "领展房产基金"),
        ("01972", "太古地产"),
        ("01997", "九龙仓置业"),
        ("00001", "长和"),
        ("00002", "中电控股"),
        ("00003", "香港中华煤气"),
        ("00066", "港铁公司"),
        ("00027", "银河娱乐"),
        ("01928", "金沙中国"),
        ("02007", "碧桂园"),
        ("02202", "万科企业"),
        ("00688", "中国海外发展"),
        ("01109", "华润置地"),
        ("00191", "丽珠医药"),
        ("00874", "白云山"),
        ("01099", "国药控股"),
        ("01177", "中国生物制药"),
        ("01093", "石药集团"),
        ("01513", "丽珠医药"),
        ("01772", "赣锋锂业"),
        ("01818", "招金矿业"),
        ("01787", "山东黄金"),
        ("01766", "中国中车"),
        ("02333", "长城汽车"),
        ("00175", "吉利汽车"),
        ("01211", "比亚迪股份"),
        ("01238", "广汽集团"),
        ("02015", "理想汽车-W"),
        ("09866", "蔚来-SW"),
        ("09868", "小鹏汽车-W"),
        ("09626", "哔哩哔哩-W"),
        ("09888", "百度集团-SW"),
        ("09999", "网易-S"),
        ("06690", "海尔智家"),
        ("02020", "安踏体育"),
        ("02331", "李宁"),
        ("02319", "蒙牛乳业"),
        ("00291", "华润啤酒"),
        ("00293", "国泰航空"),
        ("00322", "康师傅控股"),
        ("00151", "中国旺旺"),
        ("01579", "颐海国际"),
        ("06862", "海底捞"),
        ("01585", "雅迪控股"),
        ("01999", "敏华控股"),
        ("00656", "复星国际"),
        ("02196", "复星医药"),
        ("06098", "碧桂园服务"),
        ("02618", "京东物流"),
        ("06060", "众安在线"),
        ("06088", "福耀玻璃"),
        ("09961", "携程集团-S"),
        ("00960", "龙湖集团"),
        ("01044", "恒安国际"),
        ("01951", "锦欣生殖"),
        ("02013", "微盟集团"),
        ("01258", "中国有色矿业"),
        ("01378", "中国宏桥"),
        ("02688", "新奥能源"),
        ("01193", "华润燃气"),
        ("00836", "华润电力"),
        ("00956", "新天绿色能源"),
        ("00358", "江西铜业股份"),
        ("00392", "北京控股"),
        ("01336", "新华保险"),
        ("02628", "中国人寿"),
        ("02601", "中国太保"),
        ("01339", "中国人民保险集团"),
        ("02380", "中国电力"),
        ("00921", "海信家电"),
        ("00019", "太古股份公司A"),
        ("00669", "创科实业"),
        ("00708", "恒大汽车"),
        ("02382", "舜宇光学科技"),
        ("02018", "瑞声科技"),
        ("00285", "比亚迪电子"),
        ("01876", "百济神州"),
        ("02269", "药明生物"),
        ("02359", "药明康德"),
        ("06160", "百济神州-W"),
        ("01877", "君实生物"),
        ("01347", "华虹半导体"),
        ("00981", "中芯国际"),
        ("03888", "金山软件"),
        ("00268", "金蝶国际"),
        ("01448", "福寿园"),
        ("01117", "现代牧业"),
        ("01055", "中国南方航空"),
        ("00753", "中国国航"),
        ("01057", "浙江世宝"),
        ("00551", "裕元集团"),
        ("00552", "中国通信服务"),
        ("00135", "昆仑能源"),
        ("00144", "招商局港口"),
        ("00330", "思捷环球"),
        ("00522", "ASMPT"),
        ("00998", "嘉里物流"),
        ("02768", "佳源国际"),
    ],
    "US": [
        ("AAPL", "Apple"),
        ("MSFT", "Microsoft"),
        ("GOOGL", "Alphabet"),
        ("GOOG", "Alphabet"),
        ("AMZN", "Amazon"),
        ("NVDA", "NVIDIA"),
        ("META", "Meta Platforms"),
        ("TSLA", "Tesla"),
        ("BRK.B", "Berkshire Hathaway"),
        ("JPM", "JPMorgan Chase"),
        ("V", "Visa"),
        ("JNJ", "Johnson & Johnson"),
        ("WMT", "Walmart"),
        ("MA", "Mastercard"),
        ("PG", "Procter & Gamble"),
        ("UNH", "UnitedHealth"),
        ("HD", "Home Depot"),
        ("BAC", "Bank of America"),
        ("XOM", "Exxon Mobil"),
        ("KO", "Coca-Cola"),
        ("PEP", "PepsiCo"),
        ("COST", "Costco"),
        ("DIS", "Disney"),
        ("NFLX", "Netflix"),
        ("ADBE", "Adobe"),
        ("CRM", "Salesforce"),
        ("INTC", "Intel"),
        ("AMD", "AMD"),
        ("QCOM", "Qualcomm"),
        ("ORCL", "Oracle"),
        ("CSCO", "Cisco"),
        ("IBM", "IBM"),
        ("TXN", "Texas Instruments"),
        ("PYPL", "PayPal"),
        ("NKE", "Nike"),
        ("MCD", "McDonald's"),
        ("SBUX", "Starbucks"),
        ("BA", "Boeing"),
        ("GE", "General Electric"),
        ("UPS", "United Parcel Service"),
        ("CAT", "Caterpillar"),
        ("GS", "Goldman Sachs"),
        ("MS", "Morgan Stanley"),
        ("C", "Citigroup"),
        ("WFC", "Wells Fargo"),
        ("T", "AT&T"),
        ("VZ", "Verizon"),
        ("PFE", "Pfizer"),
        ("MRK", "Merck"),
        ("ABBV", "AbbVie"),
        ("LLY", "Eli Lilly"),
        ("TMO", "Thermo Fisher"),
        ("ABT", "Abbott"),
        ("NEE", "NextEra Energy"),
        ("DUK", "Duke Energy"),
        ("SO", "Southern Company"),
        ("BMY", "Bristol-Myers Squibb"),
        ("AMGN", "Amgen"),
        ("GILD", "Gilead"),
        ("CVS", "CVS Health"),
        ("UNP", "Union Pacific"),
        ("LMT", "Lockheed Martin"),
        ("RTX", "Raytheon"),
        ("AVGO", "Broadcom"),
        ("NOW", "ServiceNow"),
        ("SHOP", "Shopify"),
        ("SNAP", "Snap"),
        ("TWLO", "Twilio"),
        ("SQ", "Block"),
        ("COIN", "Coinbase"),
        ("ROKU", "Roku"),
        ("SPOT", "Spotify"),
        ("UBER", "Uber"),
        ("LYFT", "Lyft"),
        ("ABNB", "Airbnb"),
        ("DASH", "DoorDash"),
        ("RBLX", "Roblox"),
        ("PINS", "Pinterest"),
        ("ZM", "Zoom"),
        ("DOCU", "DocuSign"),
        ("OKTA", "Okta"),
        ("CRWD", "CrowdStrike"),
        ("SNOW", "Snowflake"),
        ("PLTR", "Palantir"),
        ("HOOD", "Robinhood"),
        ("RIVN", "Rivian"),
        ("LCID", "Lucid"),
        ("F", "Ford"),
        ("GM", "General Motors"),
        ("STLA", "Stellantis"),
        ("TM", "Toyota"),
        ("BABA", "Alibaba"),
        ("JD", "JD.com"),
        ("NIO", "NIO"),
        ("XPEV", "XPeng"),
        ("LI", "Li Auto"),
        ("BIDU", "Baidu"),
        ("PDD", "Pinduoduo"),
        ("TME", "Tencent Music"),
        ("BILI", "Bilibili"),
        ("NTES", "NetEase"),
        ("EDU", "New Oriental"),
        ("TAL", "TAL Education"),
        ("FUTU", "Futu"),
        ("TIGR", "Tiger Brokers"),
        ("MNSO", "MINISO"),
        ("YUMC", "Yum China"),
        ("ZTO", "ZTO Express"),
        ("YMM", "Full Truck Alliance"),
        ("SE", "Sea Limited"),
        ("GRAB", "Grab"),
        ("PLUG", "Plug Power"),
        ("RIOT", "Riot Platforms"),
        ("MARA", "Marathon Digital"),
        ("MSTR", "MicroStrategy"),
        ("GLD", "SPDR Gold"),
        ("SLV", "iShares Silver"),
        ("SPY", "SPDR S&P 500"),
        ("QQQ", "Invesco QQQ"),
        ("VOO", "Vanguard S&P 500"),
        ("IWM", "iShares Russell 2000"),
        ("ARKK", "ARK Innovation"),
        ("TLT", "iShares 20+ Treasury"),
        ("EEM", "iShares MSCI Emerging"),
    ],
}
